//! vigild's half of the wire contract, as a file other languages read.
//!
//! vigild serves `Snapshot` on its socket; vigil-core (C#) reads it with its own copy of these
//! types. A comment asking for both to be changed together is not an enforcer, so this module
//! generates `daemon/contract.json` from the Rust types and fails if the file on disk is out of
//! date, and vigil-core's `ContractTests` round-trips every sample in it through the C# types.
//! vigil-core's own stream to the browser is a separate contract: it writes
//! `core/contract.json`, which the web reads.
//!
//! Adding or renaming a field is therefore a three-part change in one commit: the Rust type,
//! the regenerated contract file (`cargo test -p vigild` writes it), and the C# type. Miss any
//! one and CI fails.

use super::{DriveHealth, FanStatus, PwmMode, STREAM_KEEPALIVE_SECONDS, SensorCategory, SensorReading, Snapshot};
use serde_json::{Value, json};

const CONTRACT_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/contract.json");

// Every variant of every wire enum. The `_exhaustive` guards below stop compiling when a
// variant is added without being listed here, which is the whole point of them.
const SENSOR_CATEGORIES: [SensorCategory; 6] = [
    SensorCategory::Cpu,
    SensorCategory::BoardAmbient,
    SensorCategory::Drive,
    SensorCategory::Gpu,
    SensorCategory::Memory,
    SensorCategory::Hba,
];
const PWM_MODES: [PwmMode; 6] =
    [PwmMode::Disabled, PwmMode::Manual, PwmMode::ThermalCruise, PwmMode::SpeedCruise, PwmMode::SmartFanIII, PwmMode::SmartFanIV];

fn _exhaustive_sensor_category(value: SensorCategory) {
    use SensorCategory::{BoardAmbient, Cpu, Drive, Gpu, Hba, Memory};
    match value {
        Cpu | BoardAmbient | Drive | Gpu | Memory | Hba => (),
    }
}

fn _exhaustive_pwm_mode(value: PwmMode) {
    use PwmMode::{Disabled, Manual, SmartFanIII, SmartFanIV, SpeedCruise, ThermalCruise};
    match value {
        Disabled | Manual | ThermalCruise | SpeedCruise | SmartFanIII | SmartFanIV => (),
    }
}

/// Every field populated, including the optional ones: a `None` would serialize to `null` and
/// tell the other side nothing about the field's type.
fn samples() -> Value {
    let sensor = SensorReading {
        id: "drive:naa.5000c500bae40598".to_owned(),
        category: SensorCategory::Drive,
        label: "naa.5000c500bae40598".to_owned(),
        celsius_or_null: Some(35.5),
        source_path: "/sys/class/hwmon/hwmon4/temp1_input".to_owned(),
        is_available: true,
        port: Some("pci-0000:01:00.1-ata-3".to_owned()),
    };
    let fan = FanStatus { id: "drive-cage".to_owned(), duty_percent: 65, rpm: Some(1211), mode: Some(PwmMode::Manual), stalled: false };
    let drive_health = DriveHealth {
        device_name: "naa.5000c500bae40598".to_owned(),
        port: Some("pci-0000:01:00.1-ata-3".to_owned()),
        passed: Some(true),
        reallocated_sector_count: Some(0),
        pending_sector_count: Some(0),
        power_on_hours: Some(8760),
        source_path: "/dev/sdc".to_owned(),
        is_available: true,
        as_of: "2026-09-21T23:00:38.412Z".to_owned(),
    };
    let snapshot = Snapshot {
        timestamp_utc: "2026-09-21T23:01:34.155Z".to_owned(),
        sensors: vec![sensor.clone()],
        fans: vec![fan.clone()],
        drive_health: vec![drive_health.clone()],
        control_loop_healthy: true,
    };

    json!({
        "$comment": "GENERATED by `cargo test -p vigild` from daemon/src/protocol/mod.rs. \
                     Do not edit by hand. This is vigild's half of the wire contract: \
                     vigil-core's ContractTests check its C# client types against it. \
                     vigil-core's own stream is pinned separately, in core/contract.json. \
                     See docs/STYLE.md §1.3.",
        "enums": {
            "SensorCategory": SENSOR_CATEGORIES,
            "PwmMode": PWM_MODES,
        },
        "types": {
            "SensorReading": sensor,
            "FanStatus": fan,
            "DriveHealth": drive_health,
            "Snapshot": snapshot,
        },
        // vigil-core's read timeout on /events must exceed twice this, and its tests check it.
        "limits": {
            "streamKeepaliveSeconds": STREAM_KEEPALIVE_SECONDS,
        },
    })
}

#[test]
fn contract_json_is_current() {
    let expected = format!("{}\n", serde_json::to_string_pretty(&samples()).expect("the contract must serialize"));
    let actual = std::fs::read_to_string(CONTRACT_PATH).unwrap_or_default();

    if actual != expected {
        std::fs::write(CONTRACT_PATH, &expected).expect("could not write the contract file");
        panic!(
            "daemon/contract.json was out of date and has been regenerated.\n\
             Commit it, and make the matching change to vigil-core's C# types.\n\
             See docs/STYLE.md §1.3."
        );
    }
}

#[test]
fn every_sample_populates_every_optional_field() {
    // A null in the contract would tell the C# side nothing about that field's type,
    // so the generator must never emit one.
    fn find_null(value: &Value, path: &str, found: &mut Vec<String>) {
        match value {
            Value::Null => found.push(path.to_owned()),
            Value::Object(map) => {
                for (key, child) in map {
                    find_null(child, &format!("{path}.{key}"), found);
                }
            }
            Value::Array(items) => {
                for (index, child) in items.iter().enumerate() {
                    find_null(child, &format!("{path}[{index}]"), found);
                }
            }
            _ => {}
        }
    }

    let mut nulls = Vec::new();
    find_null(&samples(), "contract", &mut nulls);
    assert!(nulls.is_empty(), "the contract must populate every field, but these are null: {nulls:?}");
}
