using System.Reflection;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using Vigil.Core.Protocol;
using Xunit;

namespace Vigil.Core.Tests;

/// <summary>
/// vigil-core's half of the wire contract: what it streams to the browser. This test writes
/// core/contract.json from the C# types, and web/src/lib/types.contract.test.ts checks the
/// TypeScript mirror against it (docs/STYLE.md §1.3).
/// </summary>
/// <remarks>
/// Changing a wire type is a three-part change in one commit: the C# record, the regenerated
/// file (running these tests writes it, and fails once so the change cannot go unnoticed), and
/// web/src/lib/types.ts. Miss any one and CI fails.
/// </remarks>
public sealed class CoreContractTests
{
    private const string Comment =
        "vigil-core's half of the wire contract: what it sends the browser on /api/live and /api/events. "
        + "Generated by the vigil-core tests (dotnet run --project core/Vigil.Core.Tests) from the C# types; "
        + "do not edit. The snapshot inside liveMessages.snapshot is vigild's, whose own half is "
        + "daemon/contract.json. web/src/lib/types.contract.test.ts reads both.";

    /// <summary>
    /// Indented, and with the relaxed encoder so the file reads as written ("vigild's" rather
    /// than an escaped apostrophe): it is a file for people and the web test, never put in HTML.
    /// </summary>
    private static readonly JsonSerializerOptions Pretty = new(VigilJson.Options)
    {
        WriteIndented = true,
        IndentSize = 2,
        NewLine = "\n",
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    /// <summary>Every field populated: a null would tell the other side nothing about the field's type.</summary>
    private static readonly UpsReading Reading = new()
    {
        TimestampUtc = "2026-09-21T23:01:34.155Z",
        Name = "apc",
        Model = "American Power Conversion Smart-UPS 1000",
        Status = ["OL"],
        BatteryCharge = 100.5,
        BatteryRuntimeSeconds = 2310.5,
        Load = 25.5,
        RealPower = 168.5,
        InputVoltage = 231.4,
        OutputVoltage = 230.5,
        BatteryVoltage = 27.3,
        BatteryTemperature = 34.5,
        BatteryDate = "2026-08-15",
        LowBatteryRuntimeSeconds = 600.5,
        LowBatteryCharge = 30.5,
        TransferReason = "LowInputVoltage",
        OutputFrequency = 49.97,
        OutputCurrent = 0.81,
        Monitors = 1,
        Variables = new SortedDictionary<string, string>(StringComparer.Ordinal) { ["ups.status"] = "OL" },
    };

    private static readonly UpsLimits Limits = new() { HostShutdownSeconds = 84.5, BatteryTemperatureWarn = 40.5 };

    private static readonly UpsState Ups = new() { Enabled = true, Name = "apc", Reading = Reading, Error = "upsd: DATA-STALE", Limits = Limits };

    private static readonly DriveState Drive = new()
    {
        Wwn = "naa.5000c500bae40598",
        Port = "pci-0000:01:00.1-ata-3",
        Passed = true,
        ReallocatedSectorCount = 0,
        PendingSectorCount = 0,
        PowerOnHours = 8760,
        SourcePath = "/dev/sdc",
        AsOf = "2026-09-21T23:00:38.412Z",
    };

    private static readonly EventRecord Event = new()
    {
        Id = 1,
        Ts = "2026-09-21T23:01:34.155Z",
        Severity = Severity.Warning,
        Kind = "fan-stalled:drive-cage",
        Message = "drive-cage is being driven at 65% but reads 0 RPM",
    };

    private static readonly Dictionary<string, LiveMessage> LiveMessages = new(StringComparer.Ordinal)
    {
        ["snapshot"] = new SnapshotMessage { Snapshot = VigildSnapshot() },
        ["daemon"] = new DaemonMessage { Connected = true },
        ["event"] = new EventMessage { Event = Event },
        ["drives"] = new DrivesMessage { Drives = [Drive] },
        ["ups"] = new UpsMessage { Ups = Ups },
    };

    /// <summary>vigild's own sample, so the snapshot inside the stream is the one Rust generated.</summary>
    private static Snapshot VigildSnapshot() =>
        ContractFiles.Load(ContractFiles.Daemon)["types"]!["Snapshot"].Deserialize<Snapshot>(VigilJson.Options)
        ?? throw new InvalidOperationException("daemon/contract.json has no Snapshot sample");

    private static JsonNode Node<T>(T value) => JsonSerializer.SerializeToNode(value, VigilJson.Options)!;

    private static JsonObject Generate() => new()
    {
        ["$comment"] = Comment,
        ["enums"] = new JsonObject
        {
            [nameof(Severity)] = new JsonArray([.. Enum.GetValues<Severity>().Select(severity => Node(severity))]),
        },
        ["types"] = new JsonObject
        {
            [nameof(UpsReading)] = Node(Reading),
            [nameof(UpsLimits)] = Node(Limits),
            [nameof(UpsState)] = Node(Ups),
            [nameof(DriveState)] = Node(Drive),
            [nameof(EventRecord)] = Node(Event),
        },
        ["liveMessages"] = new JsonObject(LiveMessages.Select(entry => KeyValuePair.Create(entry.Key, (JsonNode?)Node(entry.Value)))),
    };

    [Fact]
    public void TheContractFileIsCurrent()
    {
        var generated = Generate().ToJsonString(Pretty) + "\n";
        var onDisk = File.Exists(ContractFiles.Core) ? File.ReadAllText(ContractFiles.Core).ReplaceLineEndings("\n") : string.Empty;

        if (generated != onDisk)
        {
            File.WriteAllText(ContractFiles.Core, generated);
            Assert.Fail(
                "core/contract.json was out of date and has been rewritten. Commit it, and if the web contract test "
                + "now fails, update web/src/lib/types.ts to match.");
        }
    }

    [Fact]
    public void EveryLiveMessageVariantHasASample()
    {
        // A variant added to LiveMessage with no sample here would never reach the contract,
        // and the web would never be told about it.
        var variants = typeof(LiveMessage).GetCustomAttributes<JsonDerivedTypeAttribute>()
            .Select(attribute => (string)attribute.TypeDiscriminator!)
            .Order(StringComparer.Ordinal);

        Assert.Equal(variants, LiveMessages.Keys.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void EveryLiveMessageReadsBackThroughItsDiscriminatorWithTypeFirst()
    {
        foreach (var (tag, message) in LiveMessages)
        {
            var json = JsonSerializer.Serialize(message, VigilJson.Options);

            Assert.StartsWith($$"""{"type":"{{tag}}" """.TrimEnd(), json, StringComparison.Ordinal);
            var parsed = JsonSerializer.Deserialize<LiveMessage>(json, VigilJson.Options);
            Assert.Equal(json, JsonSerializer.Serialize(parsed, VigilJson.Options));
        }
    }
}
