#!/usr/bin/env bash
# Every check for vigil, in one place. CI runs this script and nothing else, so what passes
# locally is exactly what passes in CI (docs/DECISIONS.md ADR-012).
#
#   scripts/check.sh              run everything installed, skip what is not
#   CHECK_STRICT=1 scripts/check.sh   a missing tool is a failure (this is what CI uses)
#   scripts/check.sh --rust|--web|--rules   just that section
#
# Checks marked PENDING report known outstanding findings without failing: they are debt
# docs/CLEANUP.md already tracks, and they become hard failures when their phase lands.

set -uo pipefail
cd "$(dirname "$0")/.."

readonly RED=$'\033[31m' GREEN=$'\033[32m' YELLOW=$'\033[33m' DIM=$'\033[2m' OFF=$'\033[0m'
failures=0
skipped=0
pending=0

pass()    { printf '  %s✓%s %s\n' "$GREEN" "$OFF" "$1"; }
fail()    { printf '  %s✗%s %s\n' "$RED" "$OFF" "$1"; failures=$((failures + 1)); }
warn()    { printf '  %s!%s %s\n' "$YELLOW" "$OFF" "$1"; }
note()    { printf '    %s%s%s\n' "$DIM" "$1" "$OFF"; }
section() { printf '\n%s\n' "$1"; }

# PENDING: a known finding tracked in docs/CLEANUP.md. Reported every run, never silent,
# but not a failure until its phase lands.
todo() { printf '  %s·%s %s %s(pending: %s)%s\n' "$YELLOW" "$OFF" "$1" "$DIM" "$2" "$OFF"; pending=$((pending + 1)); }

have() {
	if command -v "$1" >/dev/null 2>&1; then return 0; fi
	if [ "${CHECK_STRICT:-0}" = "1" ]; then fail "$1 is not installed"; else warn "$1 is not installed, skipping"; skipped=$((skipped + 1)); fi
	return 1
}

run() { # run <label> <command...>
	local label=$1; shift
	local output
	if output=$("$@" 2>&1); then pass "$label"; else fail "$label"; printf '%s\n' "$output" | sed 's/^/    /' | tail -40; fi
}

want_rust=1 want_dotnet=1 want_web=1 want_rules=1
case "${1:-}" in
	--rust)   want_dotnet=0 want_web=0 want_rules=0 ;;
	--dotnet) want_rust=0 want_web=0 want_rules=0 ;;
	--web)    want_rust=0 want_dotnet=0 want_rules=0 ;;
	--rules)  want_rust=0 want_dotnet=0 want_web=0 ;;
	"") ;;
	*) printf 'usage: %s [--rust|--dotnet|--web|--rules]\n' "$0" >&2; exit 2 ;;
esac

# ----------------------------------------------------------------- Rust
if [ "$want_rust" = 1 ]; then
	section 'Rust'
	if have cargo; then
		run 'cargo fmt'                  cargo fmt --all --check
		run 'cargo clippy'               cargo clippy --workspace --all-targets --no-deps
		# Also regenerates protocol/contract.json and fails if it was stale (STYLE.md §1.3).
		run 'cargo test'                 cargo test --workspace
		if ! git diff --quiet -- protocol/contract.json 2>/dev/null; then
			fail 'protocol/contract.json was regenerated by the tests: commit it, and make the matching change to web/src/lib/types.ts'
		else
			pass 'protocol/contract.json is current'
		fi
		if cargo deny --version >/dev/null 2>&1; then
			run 'cargo deny'             cargo deny --all-features check
		elif [ "${CHECK_STRICT:-0}" = "1" ]; then
			fail 'cargo-deny is not installed (cargo install cargo-deny --locked)'
		else
			warn 'cargo-deny is not installed, skipping (cargo install cargo-deny --locked)'; skipped=$((skipped + 1))
		fi
	fi
fi

# ----------------------------------------------------------------- .NET
if [ "$want_dotnet" = 1 ]; then
	section '.NET (vigil-core)'
	if have dotnet; then
		# Formatting, the same split as the Rust half: the build enforces correctness (warnings
		# are errors there), this enforces style.
		run 'dotnet format' dotnet format core-net --verify-no-changes
		run 'dotnet build'  dotnet build core-net --nologo -v q
		# `dotnet run` rather than `dotnet test`: xunit.v3 runs on Microsoft.Testing.Platform,
		# which builds the test project as an executable, and on this SDK `dotnet test`'s bridge
		# to it discovers zero tests while the runner itself finds them all. Running the runner
		# is both reliable and faster.
		run 'dotnet test'   dotnet run --project core-net/Vigil.Core.Tests --no-build -v q
	fi
fi

# ----------------------------------------------------------------- Web
if [ "$want_web" = 1 ]; then
	section 'Web'
	if have npm; then
		if [ ! -d web/node_modules ]; then
			warn 'web/node_modules is missing, skipping (cd web && npm install)'; skipped=$((skipped + 1))
		else
			run 'prettier'     npm --prefix web run --silent lint
			run 'svelte-check' npm --prefix web run --silent check
			run 'vitest'       npm --prefix web run --silent test
			# Low-severity advisories with no upstream fix are accepted; see ADR-014.
			run 'npm audit'    npm --prefix web audit --audit-level=moderate
		fi
	fi
fi

# ----------------------------------------------------------------- Project rules
# The rules from docs/STYLE.md and docs/SECURITY.md that a grep can actually check. A rule
# with no enforcer gets deleted from the guide, so this section is the guide's teeth.
if [ "$want_rules" = 1 ]; then
	section 'Project rules'

	# tracing discards every record until a subscriber is installed, so a binary that forgets
	# to call vigil_logging::init runs completely silently - which is exactly what happened
	# when the logger was migrated, and no test noticed.
	missing_init=''
	for entry in daemon/src/main.rs core/src/main.rs; do
		grep -q 'vigil_logging::init' "$entry" || missing_init="$missing_init $entry"
	done
	if [ -z "$missing_init" ]; then
		pass 'every binary installs a tracing subscriber'
	else
		fail 'a binary never installs a tracing subscriber, so it would log nothing:'
		for entry in $missing_init; do printf '    %s\n' "$entry"; done
	fi

	# SECURITY.md §3.2: a root daemon does not listen on a port. There must be no TCP code
	# path in the daemon at all, so there is nothing to misconfigure.
	if grep -rn 'TcpListener\|TcpStream' daemon/src >/dev/null 2>&1; then
		fail 'daemon/ contains TCP code: vigild must only ever serve a unix socket (SECURITY.md §3.2)'
		grep -rn 'TcpListener\|TcpStream' daemon/src | sed 's/^/    /'
	else
		pass 'vigild has no TCP code path'
	fi

	# SECURITY.md §5: subprocesses are argv, never a shell.
	if grep -rnE '"(sh|bash|cmd)"|Command::new\("sh"\)|-c".*\$' --include='*.rs' --include='*.ts' daemon/src core/src web/src >/dev/null 2>&1; then
		fail 'a subprocess looks like it goes through a shell: use argv (SECURITY.md §5)'
		grep -rnE '"(sh|bash|cmd)"' --include='*.rs' --include='*.ts' daemon/src core/src web/src | sed 's/^/    /'
	else
		pass 'no subprocess goes through a shell'
	fi

	# SECURITY.md §7: no credential ever reaches the repo. The dev compose file's throwaway
	# password is the one allowed exception (it binds 127.0.0.1 and is never deployed).
	if grep -rnE 'postgres://[^:@/ ]+:[^@/ ]+@' --include='*.rs' --include='*.ts' --include='*.env' --include='*.toml' \
		--include='*.service' . 2>/dev/null | grep -v '^./target' | grep -v ':PASSWORD@' | grep -v 'vigil:vigil@127.0.0.1' | grep -v node_modules >/dev/null; then
		fail 'what looks like a real credential is committed (SECURITY.md §7)'
		grep -rnE 'postgres://[^:@/ ]+:[^@/ ]+@' --include='*.rs' --include='*.ts' --include='*.env' --include='*.toml' \
			--include='*.service' . 2>/dev/null | grep -v '^./target' | grep -v ':PASSWORD@' | grep -v 'vigil:vigil@127.0.0.1' | grep -v node_modules | sed 's/^/    /'
	else
		pass 'no credential is committed'
	fi

	# ARCHITECTURE.md: dependencies point inward. Nothing shared may import a binary crate.
	shared_leak=0
	for crate in vigil-protocol; do
		if cargo tree -p "$crate" --prefix none 2>/dev/null | grep -qE '^(vigild|vigil-core) '; then
			fail "$crate depends on a binary crate: dependencies point inward (ARCHITECTURE.md)"
			shared_leak=1
		fi
	done
	[ "$shared_leak" = 0 ] && pass 'dependencies point inward'

	# What the .gitattributes drift looked like: patterns naming a directory that no longer
	# exists. `dashboard/**` outlived the rename to `web/` by five commits.
	stale=0
	while read -r pattern; do
		[ -z "$pattern" ] && continue
		dir=${pattern%%/**}
		[ "$dir" = "$pattern" ] && continue
		if [ ! -e "$dir" ]; then fail ".gitattributes names '$dir', which does not exist"; stale=1; fi
	done < <(grep -oE '^[^ 	#]+/\*\*' .gitattributes 2>/dev/null)
	[ "$stale" = 0 ] && pass '.gitattributes names only paths that exist'

	# STYLE.md §2.1: a soft ceiling. Over it, a file either gets split or says near the top
	# why it stays whole - a file that cites §2.1 in its first 40 lines has made that case and
	# is not listed, so what remains is the files nobody has looked at.
	over_ceiling=''
	while IFS= read -r entry; do
		[ -n "$entry" ] || continue
		source=${entry#*	}
		head -40 "$source" | grep -q 'STYLE.md §2.1' && continue
		over_ceiling="$over_ceiling$entry
"
	done <<-EOF
		$(find protocol/src daemon/src core/src web/src -type f \( -name '*.rs' -o -name '*.ts' -o -name '*.svelte' \) \
			-exec awk 'END { if (NR > 400) print NR"\t"FILENAME }' {} \; 2>/dev/null | sort -rn)
	EOF
	if [ -n "$over_ceiling" ]; then
		warn "$(printf '%s' "$over_ceiling" | grep -c . ) file(s) over the 400-line ceiling with no reason given (STYLE.md §2.1)"
		printf '%s' "$over_ceiling" | sed 's/^/    /'
	else
		pass 'every file is under the 400-line ceiling, or says why not'
	fi

	# ---- Checks whose findings are tracked debt, reported every run until their phase lands.

	# STYLE.md §3.3 / SECURITY.md §6: a VALUE is never formatted into a statement. The
	# detectable shape of that mistake is a quoted interpolation ('{...}'), since an unquoted
	# one is an identifier, which cannot be bound at all.
	#
	# Scoped to the modules whose strings are all SQL: elsewhere '{x}' is almost always an
	# error message, and a check that cries wolf gets ignored. A site that genuinely has to
	# interpolate - a DDL identifier from a compile-time constant - says so with a
	# `sql-literal-ok:` comment giving the reason, which is the justification the guide asks
	# for rather than a silent exemption.
	unjustified_sql=''

	# The C# equivalent: a command built from an interpolated string. Precise, because that is
	# exactly the shape of the mistake - `CreateCommand($"...")` with a variable in it.
	for source in $(find core-net -name '*.cs' -not -path '*/obj/*' -not -path '*/bin/*' 2>/dev/null); do
		while IFS=: read -r line _; do
			[ -n "$line" ] || continue
			start=$((line > 6 ? line - 6 : 1))
			sed -n "${start},${line}p" "$source" | grep -q 'sql-literal-ok' || unjustified_sql="$unjustified_sql $source:$line"
		done <<-EOF
			$(grep -nE '(CreateCommand|NpgsqlCommand)\(\$"' "$source" 2>/dev/null | cut -d: -f1 | sed 's/$/:/')
		EOF
	done

	for source in core/src/db.rs core/src/timescale.rs; do
		[ -f "$source" ] || continue
		while IFS=: read -r line _; do
			[ -n "$line" ] || continue
			# The marker may be on the line itself or anywhere in the comment block above
			# it - the window spans a whole statement, since one format! string can hold several
			# interpolations and the reason is written once for all of them.
			start=$((line > 24 ? line - 24 : 1))
			sed -n "${start},${line}p" "$source" | grep -q 'sql-literal-ok' || unjustified_sql="$unjustified_sql $source:$line"
		done <<-EOF
			$(grep -nE "'\{[A-Za-z_]" "$source" 2>/dev/null | cut -d: -f1 | sed 's/$/:/')
		EOF
	done
	if [ -z "$unjustified_sql" ]; then
		pass 'no SQL interpolates a value without justifying it'
	else
		fail 'a value is formatted into a SQL statement with no `sql-literal-ok:` reason (STYLE.md §3.3):'
		for entry in $unjustified_sql; do printf '    %s\n' "$entry"; done
	fi

	# SECURITY.md §3.3: the systemd hardening baseline. A directive may be absent ONLY if the
	# unit says why in a `# <Directive>: NOT set, <reason>` comment - some of them genuinely
	# break a component (ProtectKernelTunables stops vigild writing /sys, MemoryDenyWriteExecute
	# stops node starting), and the guide's rule is that an omission is documented, not silent.
	missing_units=''
	for unit in deploy/vigild.service core/deploy/vigil-core.service web/deploy/vigil-web.service; do
		[ -f "$unit" ] || continue
		for directive in NoNewPrivileges ProtectSystem ProtectHome PrivateTmp ProtectKernelTunables \
			ProtectKernelModules ProtectControlGroups RestrictAddressFamilies RestrictNamespaces \
			RestrictSUIDSGID SystemCallArchitectures LockPersonality MemoryDenyWriteExecute \
			CapabilityBoundingSet; do
			grep -q "^$directive=" "$unit" && continue
			grep -qE "^# *$directive: NOT set" "$unit" && continue
			missing_units="$missing_units $unit:$directive"
		done
	done
	if [ -z "$missing_units" ]; then
		pass 'every unit carries the hardening baseline, or documents the omission'
	else
		fail "hardening directive(s) neither set nor documented as omitted (SECURITY.md §3.3):"
		for entry in $missing_units; do printf '    %s\n' "$entry"; done
	fi

	# SECURITY.md §6: every database connection bounds its statements.
	if grep -rq 'statement_timeout' web/src/lib/server/db.ts 2>/dev/null; then
		pass 'vigil-web bounds its database statements'
	else
		todo 'vigil-web sets no statement_timeout (SECURITY.md §6)' 'CLEANUP.md phase 1'
	fi

	# SECURITY.md §8: the browser gets security headers.
	if grep -rq 'Content-Security-Policy\|csp' web/src/hooks.server.ts web/vite.config.ts 2>/dev/null; then
		pass 'vigil-web sets security headers'
	else
		todo 'vigil-web sets no CSP or security headers (SECURITY.md §8)' 'CLEANUP.md phase 1'
	fi
fi

# ----------------------------------------------------------------- Result
section 'Result'
[ "$pending" -gt 0 ] && note "$pending tracked finding(s) pending, see docs/CLEANUP.md"
[ "$skipped" -gt 0 ] && note "$skipped check(s) skipped; CHECK_STRICT=1 makes a missing tool a failure"
if [ "$failures" -gt 0 ]; then
	printf '  %s%d check(s) failed%s\n\n' "$RED" "$failures" "$OFF"
	exit 1
fi
printf '  %sall checks passed%s\n\n' "$GREEN" "$OFF"
